# Generated by Django 3.2.16 on 2022-11-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина 150', max_length=150, unique=True, verbose_name='название')),
                ('email', models.EmailField(help_text='Максимум 320 символов', max_length=320, verbose_name='Почта')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
