# Generated by Django 3.2.16 on 2022-11-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Максимум 320 символов', max_length=320, null=True, verbose_name='Почта'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Максимальная длина 150', max_length=150, null=True, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
