# Generated by Django 3.2.16 on 2022-11-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20221122_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'default_related_name': 'fback', 'verbose_name': 'Заявку на фидбек', 'verbose_name_plural': 'Заявки на фидбек'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(help_text='Максимум 320 символов', max_length=320, null=True, verbose_name='почта'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(help_text='Максимальная длина 150', max_length=150, null=True, unique=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
    ]
