# Generated by Django 3.2.16 on 2022-11-02 00:30

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина 150', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Максимальная длина 200', max_length=200, verbose_name='Слаг')),
                ('weight', models.SmallIntegerField(default=100, help_text='от 0 до 32767, значение по умолчанию 100', verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина 150', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(help_text='Максимальная длина 200', max_length=200, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимальная длина 150', max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('text', models.TextField(help_text='В текста должно быть слово превосходно или роскошно', validators=[catalog.validators.validate_must_be_param], verbose_name='Текст')),
                ('category', models.ForeignKey(help_text='Выберите категории', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('tags', models.ManyToManyField(help_text='Выберите тег', to='catalog.Tag', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
