# Generated by Django 3.2.16 on 2022-11-12 19:47

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('slug', models.SlugField(help_text='Максимальная длина 200', max_length=200, verbose_name='слаг')),
                ('name', models.CharField(help_text='Максимальная длина 150', max_length=150, unique=True, verbose_name='название')),
                ('weight', models.SmallIntegerField(default=100, help_text='от 0 до 32767, значение по умолчанию 100', verbose_name='вес')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('weight', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('name', models.CharField(help_text='Максимальная длина 150', max_length=150, unique=True, verbose_name='название')),
                ('text', models.TextField(help_text='В тексте должны быть слова "превосходно" или "роскошно"', validators=[catalog.validators.validate_must_be_param], verbose_name='Текст')),
                ('category', models.ForeignKey(help_text='Выберите категории', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
                'default_related_name': 'items',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('slug', models.SlugField(help_text='Максимальная длина 200', max_length=200, verbose_name='слаг')),
                ('name', models.CharField(help_text='Максимальная длина 150', max_length=150, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'default_related_name': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Preview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads/%Y/%m', verbose_name='Фото')),
                ('preview', models.OneToOneField(help_text='Выберите изображение', on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='catalog.item', verbose_name='главное изображение')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
                'default_related_name': 'photo',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(help_text='Выберите тег', related_name='items', to='catalog.Tag', verbose_name='тег'),
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='uploads/%Y/%m', verbose_name='Фото')),
                ('item', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фотогалерея',
                'default_related_name': 'gallery',
            },
        ),
    ]
