# Generated by Django 3.2.16 on 2022-11-12 20:14

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='В тексте должны быть слова "превосходно" или "роскошно"', validators=[catalog.validators.validate_must_be_param], verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='preview',
            field=models.OneToOneField(help_text='Выберите изображение', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='catalog.item', verbose_name='главное изображение'),
        ),
    ]
