# Generated by Django 3.2.16 on 2022-11-02 00:31

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(help_text='В текста должно быть слово превосходно или роскошно', validators=[catalog.validators.validate_must_be_param], verbose_name='Текст'),
        ),
    ]
