# Generated by Django 3.2.16 on 2022-12-06 13:09

import catalog.validators
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='item',
            field=models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='catalog.item', verbose_name='товар'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='В тексте должны быть слова "превосходно" или "роскошно"', validators=[catalog.validators.validate_must_be_param], verbose_name='описание'),
        ),
    ]
