# Generated by Django 3.2.16 on 2022-11-24 13:35

import catalog.validators
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_item_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='upload',
            field=models.ImageField(upload_to='uploads/%Y/%m', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='В тексте должны быть слова "превосходно" или "роскошно"', validators=[catalog.validators.validate_must_be_param], verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='mainimage',
            name='upload',
            field=models.ImageField(upload_to='uploads/%Y/%m', verbose_name='фото'),
        ),
    ]
